import { createElement } from '@lwc/engine-dom';
import Ass_3_LWC_form from 'c/ass_3_LWC_form';

describe('c-ass-3-l-w-c-form', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ass-3-l-w-c-form', {
            is: Ass_3_LWC_form
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});